/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Public and unauthenticated (the container HEALTHCHECK and the k8s liveness probe call it):
         *     `200` proves the process answers requests. It touches nothing — use `/api/v1/ready` for the
         *     database round trip.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Public and unauthenticated (the k8s readiness probe and the e2e global setup call it): `200`
         *     once a database round trip succeeds within a short budget, `503` while it does not — the pod
         *     leaves the Service until the database is back.
         */
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange credentials for a JWT
         * @description Rate-limited per client IP, and additionally throttled per account: after several
         *     consecutive failures for one email (default 5, `LOGIN_LOCKOUT_THRESHOLD`), further
         *     attempts for that account — even with the correct password — are rejected with `429`
         *     for a lockout window (default 15 min, `LOGIN_LOCKOUT_DURATION_SECONDS`). A successful
         *     login resets the counter. The in-memory lockout store admits at most
         *     `LOGIN_LOCKOUT_MAX_TRACKED` identities (default 10,000). At capacity a new identity
         *     receives `429` before password verification; existing tracked identities continue,
         *     and expired state frees capacity. This applies equally to existing and unknown emails.
         *
         *     **Email MFA (opt-in via the `MFA` feature flag):** when the account has MFA enabled,
         *     correct credentials answer `200` with an `MfaChallengeResponse` instead of tokens — a
         *     6-digit code is emailed to the account, and the client exchanges it together with the
         *     `challengeId` at `POST /api/v1/login/mfa` for the ordinary `LoginResponse`. On a
         *     deployment without outbound email (`MAIL_TRANSPORT=disabled`) an MFA-enabled login
         *     fails closed with `503`. The pending challenge store admits at most
         *     `MFA_MAX_TRACKED` challenges (default 10,000); new issuance at capacity receives
         *     `429` without sending a code, while existing challenges remain verifiable.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login/mfa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange an MFA challenge and emailed code for a JWT pair
         * @description Second login step for MFA-enabled accounts. The `challengeId` comes from the login
         *     response, the 6-digit `code` from the email. Challenges are single-use, expire after
         *     a short TTL (default 5 min, `MFA_CODE_TTL_SECONDS`), and allow a few attempts
         *     (default 5, `MFA_MAX_ATTEMPTS`); every failure mode — unknown challenge, expired,
         *     wrong code, attempts exhausted, user gone, password changed — answers the uniform `401`. Rate-limited
         *     per client IP.
         */
        post: operations["verifyMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a refresh token for a fresh access + refresh pair
         * @description Pure-sliding session renewal. Accepts a valid, unexpired, non-revoked refresh token and
         *     returns a brand-new access token and refresh token (each with a full TTL). The presented
         *     refresh token is left valid until its own expiry — it is not rotated out. Requires no
         *     `Authorization` header (the access token may already be expired). Returns `401` for a
         *     missing/invalid/expired/revoked refresh token, if the user no longer exists, or if the
         *     token's credential revision no longer matches the user's current credentials. Password
         *     changes invalidate earlier refresh tokens even within the same clock second. Legacy
         *     tokens without a credential revision require a fresh sign-in after upgrading to 0.14.1.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the bearer token (server-side denylist)
         * @description Revokes the access token carried in the `Authorization` header. If a `refreshToken` is
         *     supplied in the body, it is revoked too. The body is optional.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a self-service password reset
         * @description Normally answers `202` for a well-formed request, whether or not an account with that
         *     email exists (no account enumeration; the actual work happens asynchronously). If the
         *     account exists, a new password is generated and emailed first; only after delivery does
         *     its hash replace the old one (which stops working, and outstanding refresh tokens are
         *     invalidated). Throttled per submitted email — one request per interval
         *     (default 60 s, `PASSWORD_RESET_MIN_INTERVAL_SECONDS`) — uniformly for existing and
         *     unknown addresses, and rate-limited per client IP. The in-memory cooldown store admits
         *     at most `PASSWORD_RESET_MAX_TRACKED` identities (default 10,000). At capacity a new
         *     identity receives `429` and no reset email is scheduled; elapsed cooldowns free space.
         *     A soft-deleted account is unknown here (no password is minted or email sent, and the
         *     response follows the same acceptance and throttling rules). Answers `503` on
         *     deployments without outbound email (`MAIL_TRANSPORT=disabled`).
         */
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users (management view)
         * @description ADMIN only — the whole management surface is admin-gated; regular users keep only
         *     their self password change.
         *
         *     Supports offset pagination, sorting and filtering.
         *
         *     - Sortable fields: `id`, `name`, `email` (deliberately not `roles` — a set has no
         *       order). Default sort is `id` ascending; `id` ascending is always appended as a
         *       deterministic tiebreaker.
         *     - Filters (optional, whitelisted):
         *       - `name` / `email` — case- and accent-insensitive substring matches.
         *       - `role` — `ADMIN` (holders of the additional role) or `USER` (plain users).
         *       - `feature` + `featureEnabled` — feature-flag state (the pair must come
         *         together, `400` otherwise; `featureEnabled` is a strict boolean).
         */
        get: operations["listUsers"];
        put?: never;
        /**
         * Create a user
         * @description ADMIN only. The initial password is CLIENT-generated (the SPA's 96-bit generator) and
         *     shown to the admin exactly once — the server stores only the bcrypt hash and no
         *     response ever carries plaintext. The email is canonicalized (trimmed + lowercased);
         *     a duplicate among active accounts is a `409` (a soft-deleted account frees its email).
         */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        /**
         * Fetch a user
         * @description Target user or ADMIN (guard-before-read — an unauthorized caller 403s uniformly).
         */
        get: operations["getUser"];
        /**
         * Update a user's name, email, and roles
         * @description ADMIN only. The password is deliberately not writable here (it has its own endpoint).
         *     Demoting the LAST active administrator is a `409` — the management surface must stay
         *     reachable. An email already used by another active account is also a `409`.
         */
        put: operations["updateUser"];
        post?: never;
        /**
         * Delete a user
         * @description ADMIN only, soft delete: the account can no longer sign in, outstanding refresh
         *     tokens die (`user_gone`), the email is freed for reuse, and the user's catalog files
         *     stay with a deleted-creator marker. Deleting YOURSELF is a `403`; deleting the LAST
         *     active administrator is a `409`.
         */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/features": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Replace a user's disabled-feature set (ADMIN only)
         * @description Per-user feature flags: a **wholesale replace** of the target user's DISABLED set —
         *     an empty array re-enables everything (idempotent, a same-set re-PUT is `204` again).
         *     **ADMIN-only**; changing one's OWN flags is allowed (the users routes themselves are
         *     never feature-gated, so an admin can always find their way back). `MFA` is the one
         *     inverted-default flag: users start with it in the disabled set, and a set omitting it
         *     — the empty "re-enable everything" array included — ENABLES the login second factor.
         *     The set rides the JWT, so a change takes effect at the target's next token refresh
         *     (≤15 min) or login. Audited as `user.features_changed` on an actual change.
         */
        put: operations["setUserDisabledFeatures"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/language": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Set a user's language (target user or ADMIN)
         * @description The ONE synced per-user language: it drives the UI at sign-in (rides `LoginResponse`,
         *     applied by the SPA on login/MFA/refresh) and the language of every email sent to the
         *     user (read fresh at send time, so a change takes effect immediately for emails; the
         *     UI picks it up at the next sign-in or token refresh). **Target user or ADMIN** — the
         *     header language switcher is the self-service writer (switching while signed in also
         *     saves here); an admin may fix a mis-set language. Idempotent (a same-value re-PUT is
         *     `204` again); an unsupported code is `400`. Audited as `user.language_changed` on an
         *     actual change. Set initially at create (`UserCreateRequest.language`, default `en`);
         *     the whole-user PUT deliberately never touches it.
         */
        put: operations["setUserLanguage"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Change a user's password
         * @description Sets a new password for the user (minimum 10 characters). Only the password is
         *     changed; no other fields are touched. Requires the caller to be the target user,
         *     or to be ADMIN. When the caller changes their OWN password (even an admin),
         *     `currentPassword` is required and must match; an admin resetting another user's
         *     password omits it. A successful change invalidates all outstanding refresh tokens
         *     and pending MFA challenges, including changes within the same clock second
         *     (already-issued access tokens expire naturally within their TTL).
         */
        put: operations["changeUserPassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List teams
         * @description Any authenticated user — teams are the shared ownership/membership unit future
         *     features scope permissions to; every mutation below is ADMIN only.
         *
         *     - Sortable fields: `id`, `name`, `createdAt`, `updatedAt`. Default `id` ascending.
         *     - Filters: `name` (case- and accent-insensitive substring), `memberId` (only teams the
         *       user is a member of — the caller's own id yields "my teams").
         */
        get: operations["listTeams"];
        put?: never;
        /**
         * Create a team
         * @description ADMIN only (guarded before the body decodes — a non-admin's malformed body is still
         *     403). An optional initial roster: every id must be an active user (`400` otherwise). A
         *     case-insensitive name clash with an active team is `409`.
         */
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        /**
         * Get a team with its roster
         * @description Any authenticated user. Soft-deleted members stay in the roster, flagged `deleted`.
         */
        get: operations["getTeam"];
        /**
         * Rename / re-describe a team
         * @description ADMIN only, guard before the id lookup (uniform 403). The roster is managed per member below. A case-insensitive name clash with another active team is `409`.
         */
        put: operations["updateTeam"];
        post?: never;
        /**
         * Delete a team (soft)
         * @description ADMIN only, guard before the id lookup. Soft delete — the name is freed for reuse.
         */
        delete: operations["deleteTeam"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{id}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
                userId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a user to a team
         * @description ADMIN only. The user must be active (`404` otherwise); an existing member is `409`.
         */
        post: operations["addTeamMember"];
        /**
         * Remove a user from a team
         * @description ADMIN only. A membership that does not exist is `404` (a soft-deleted member's row can still be removed).
         */
        delete: operations["removeTeamMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List data sources
         * @description ADMIN only. An ADMIN-managed connection to an external issue tracker — Jira Cloud today
         *     (`kind: JIRA_CLOUD`).
         *
         *     - Sortable fields: `id`, `name`, `createdAt`, `updatedAt`. Default `id` ascending.
         *     - Filters: `name` (case- and accent-insensitive substring).
         */
        get: operations["listDataSources"];
        put?: never;
        /**
         * Create a data source
         * @description ADMIN only (guarded before the body decodes — a non-admin's malformed body is still
         *     403). `jira.siteUrl` must be exactly `https://<site>.atlassian.net` (origin only — the
         *     outbound allow-list boundary); it becomes the connection's identity. `jira.apiToken` is
         *     required here and never echoed back — the response carries `jira.hasApiToken` only. A
         *     case-insensitive name clash with an active data source is `409`.
         */
        post: operations["createDataSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data-sources/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test a Jira connection before saving it
         * @description ADMIN only (guarded before the body decodes), rate-limited (10/min per IP, bucket
         *     `data-source-test`). Probes each Jira endpoint the ingestion pipeline needs in sequence
         *     (at most 10s each, 30s total) and NEVER answers `502` — every probe outcome is a row in
         *     the response, `ok: false` included. `jira.apiToken` is required here (an ad-hoc test
         *     before the connection is saved).
         */
        post: operations["testDataSourceAdHoc"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data-sources/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test a saved data source's connection
         * @description ADMIN only, rate-limited (10/min per IP, bucket `data-source-test`). Uses the STORED,
         *     decrypted token — no request body. A successful `tenant_info` probe persists the
         *     resolved `cloudId` on the connection.
         */
        post: operations["testDataSourceStored"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data-sources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        /**
         * Get a data source
         * @description ADMIN only.
         */
        get: operations["getDataSource"];
        /**
         * Update a data source (full replace)
         * @description ADMIN only, guard before the id lookup (uniform 403). A changed `jira.siteUrl` is `409`
         *     — it is the connection's identity; create a new data source instead. Omitting OR
         *     blanking `jira.apiToken` keeps the current token; any other value rotates it (audited
         *     separately as `data_source.token_rotated`). Any successful update bumps
         *     `configRevision`. A case-insensitive name clash with another active data source is `409`.
         */
        put: operations["updateDataSource"];
        post?: never;
        /**
         * Delete a data source (soft)
         * @description ADMIN only, guard before the id lookup. Soft delete — disables the connection and frees its name; the raw/normalized rows are purged after a grace period once the sync-job queue lands (plan §0 A2).
         */
        delete: operations["deleteDataSource"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data-sources/{id}/sync-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        /**
         * List a data source's sync jobs
         * @description ADMIN only. History and command queue for one connection (v0.2.0 plan §9).
         *
         *     - Sortable fields: `id`, `requestedAt`. Default `-requestedAt` (newest first).
         *     - Filters: `kind` (`SYNC`/`RECONCILE`/`REPROCESS`/`PURGE`), `status`
         *       (`PENDING`/`RUNNING`/`SUCCEEDED`/`FAILED`/`CANCELLED`).
         */
        get: operations["listSyncJobs"];
        put?: never;
        /**
         * Enqueue a sync job ("Sync now" / "Reconcile now" / "Reprocess")
         * @description ADMIN only (guarded before the body decodes). `400` when the connection is disabled, or
         *     when `kind` is `PURGE` — PURGE is scheduled internally (a soft-deleted connection past
         *     its grace period) and is never requester-initiated. A second request while one is already
         *     `PENDING`/`RUNNING` for the same `(connection, kind)` is coalesced (`202`,
         *     `coalesced: true`, the EXISTING job).
         */
        post: operations["requestSyncJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data-sources/{id}/sync-jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
                jobId: number;
            };
            cookie?: never;
        };
        /**
         * Get one sync job
         * @description ADMIN only.
         */
        get: operations["getSyncJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data-sources/{id}/sync-jobs/{jobId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
                jobId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a sync job
         * @description ADMIN only. `PENDING` → `CANCELLED` immediately; `RUNNING` → `cancel_requested_at` is set
         *     and the worker honours it cooperatively on its next heartbeat tick; an already-terminal
         *     job (`SUCCEEDED`/`FAILED`/`CANCELLED`) is `409`.
         */
        post: operations["cancelSyncJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /**
             * @description Always `ok` on a 200 — a failed probe is a problem body, never a status word.
             * @example ok
             */
            status: string;
        };
        PasswordResetRequest: {
            /** Format: email */
            email: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        LoginResponse: {
            /** @description Short-lived access token; send as the `Authorization: Bearer` value. */
            token: string;
            /**
             * Format: int64
             * @description Access-token expiry as Unix epoch milliseconds.
             */
            expiresAt: number;
            /** @description Longer-lived token; POST to /api/v1/refresh to obtain a fresh pair. */
            refreshToken: string;
            /**
             * Format: int64
             * @description Refresh-token expiry as Unix epoch milliseconds.
             */
            refreshExpiresAt: number;
            /** Format: int32 */
            userId: number;
            /** @description Additional roles of the authenticated user — empty for a regular user. */
            roles: components["schemas"]["UserRole"][];
            /** @description Per-user feature flags — the admin-disabled set; empty = full access. */
            disabledFeatures: components["schemas"]["Feature"][];
            language: components["schemas"]["Language"];
        };
        /**
         * @description An additional role. Every user is implicitly a regular user; the array only ever carries privileges added on top of that baseline.
         * @enum {string}
         */
        UserRole: "ADMIN";
        /**
         * @description A per-user gateable feature. Stored as the DISABLED set (no row = enabled). MFA is the one inverted-default, login-scoped flag: users start with it disabled (email MFA is opt-in), and it gates only the login flow.
         * @enum {string}
         */
        Feature: "MFA";
        /**
         * @description A supported UI/email language. The ONE synced per-user language (V18) — set at create, changed only via PUT /users/{id}/language; drives the SPA at sign-in and every email sent to the user.
         * @enum {string}
         */
        Language: "en" | "pl";
        UserLanguageUpdateRequest: {
            language: components["schemas"]["Language"];
        };
        UserFeaturesUpdateRequest: {
            /** @description The complete new DISABLED set — an empty array enables everything. */
            disabledFeatures: components["schemas"]["Feature"][];
        };
        MfaChallengeResponse: {
            /** @description Always true — the discriminator against LoginResponse in the login 200. */
            mfaRequired: boolean;
            /** @description Opaque single-use challenge id; send it back with the emailed code. */
            challengeId: string;
            /**
             * Format: int64
             * @description Challenge (and code) expiry as Unix epoch milliseconds.
             */
            expiresAt: number;
        };
        MfaVerifyRequest: {
            challengeId: string;
            /** @description The 6-digit code from the sign-in email. */
            code: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        LogoutRequest: {
            /** @description Optional refresh token to revoke together with the access token. */
            refreshToken?: string;
        };
        UserCreateRequest: {
            name: string;
            email: string;
            /** @description Client-generated; at most 71 UTF-8 bytes (the bcrypt ceiling). Stored only as a hash and never returned. */
            password: string;
            /** @description Additional roles; omitted/empty = a regular user. */
            roles?: components["schemas"]["UserRole"][];
            /** @description Create-only (the whole-user PUT never touches it); omitted = en. */
            language?: components["schemas"]["Language"] | null;
        };
        UserUpdateRequest: {
            name: string;
            email: string;
            roles: components["schemas"]["UserRole"][];
        };
        UserResponse: {
            /** Format: int32 */
            id: number;
            name: string;
            email: string;
            /** @description Additional roles only — empty for a regular user. */
            roles: components["schemas"]["UserRole"][];
            /** @description Per-user feature flags — the admin-disabled set; empty = full access. */
            disabledFeatures: components["schemas"]["Feature"][];
            language: components["schemas"]["Language"];
        };
        UserPage: {
            items: components["schemas"]["UserResponse"][];
            page: number;
            pageSize: number;
            /**
             * Format: int64
             * @description Row count after filters, before pagination.
             */
            total: number;
        };
        PasswordUpdateRequest: {
            /** @description The new password (at least 10 characters, at most 71 UTF-8 bytes). */
            password: string;
            /** @description Required when the caller changes their OWN password (even an admin); omitted for an admin resetting somebody else's. */
            currentPassword?: string;
        };
        TeamCreateRequest: {
            name: string;
            description?: string | null;
            /** @description Optional initial roster — every id must be an active user. */
            memberIds?: number[];
        };
        TeamUpdateRequest: {
            name: string;
            description?: string | null;
        };
        TeamMemberResponse: {
            /** Format: int32 */
            userId: number;
            name: string;
            email: string;
            /** @description The user was soft-deleted after joining; the row stays for the record. */
            deleted: boolean;
        };
        TeamResponse: {
            /** Format: int32 */
            id: number;
            name: string;
            description?: string | null;
            members: components["schemas"]["TeamMemberResponse"][];
            /**
             * Format: int64
             * @description Epoch millis
             */
            createdAt: number;
            /**
             * Format: int64
             * @description Epoch millis
             */
            updatedAt: number;
        };
        TeamListItem: {
            /** Format: int32 */
            id: number;
            name: string;
            description?: string | null;
            /** @description Active members only. */
            memberCount: number;
            /** Format: int64 */
            createdAt: number;
            /** Format: int64 */
            updatedAt: number;
        };
        TeamPage: {
            items: components["schemas"]["TeamListItem"][];
            page: number;
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        JiraConnectionRequest: {
            /** @description Exactly `https://<site>.atlassian.net` — origin only, no path/query/trailing slash (the outbound allow-list boundary). Fixed at create; a PUT changing it is `409`. */
            siteUrl: string;
            /** @description The Jira service-account email. */
            email: string;
            /** @description Write-only. Required (non-blank) on create. On update, omitted OR blank keeps the current token (the SPA's masked-password field sends an empty string for "unchanged"); any other value rotates it. Never echoed back in any response. */
            apiToken?: string | null;
            projectKeys: string[];
            authScheme?: components["schemas"]["JiraAuthScheme"];
        };
        /**
         * @default BASIC
         * @enum {string}
         */
        JiraAuthScheme: "BASIC" | "BEARER";
        DataSourceRequest: {
            name: string;
            /** @default true */
            enabled: boolean;
            syncIntervalMinutes: number;
            /**
             * Format: date
             * @description ISO date (YYYY-MM-DD), not in the future and not more than 10 years back (nor before 2000-01-01). Omitted computes today minus 24 months.
             */
            backfillFrom?: string | null;
            /** @default 3 */
            reconcileHourUtc: number;
            jira: components["schemas"]["JiraConnectionRequest"];
        };
        JiraConnectionResponse: {
            siteUrl: string;
            email: string;
            /** @description The token itself is never returned. */
            hasApiToken: boolean;
            projectKeys: string[];
            authScheme: components["schemas"]["JiraAuthScheme"];
            /** @description Resolved on the first successful probe/sync (not populated by this commit's CRUD). */
            cloudId?: string | null;
        };
        /** @enum {string} */
        DataSourceState: "NEVER_SYNCED" | "CURRENT" | "STALE" | "FAILED" | "DISABLED";
        DataSourceStatus: {
            state: components["schemas"]["DataSourceState"];
            /**
             * Format: int64
             * @description Epoch millis
             */
            lastSyncStartedAt?: number | null;
            /**
             * Format: int64
             * @description Epoch millis
             */
            lastSyncSucceededAt?: number | null;
            lastSyncErrorCode?: string | null;
            consecutiveFailures: number;
            /**
             * Format: int32
             * @description The connection's currently RUNNING sync job, if any.
             */
            runningJobId?: number | null;
        };
        DataSourceResponse: {
            /** Format: int32 */
            id: number;
            /** @enum {string} */
            kind: "JIRA_CLOUD";
            name: string;
            enabled: boolean;
            syncIntervalMinutes: number;
            /** Format: date */
            backfillFrom: string;
            reconcileHourUtc: number;
            /** Format: int64 */
            configRevision: number;
            jira: components["schemas"]["JiraConnectionResponse"];
            status: components["schemas"]["DataSourceStatus"];
            /**
             * Format: int64
             * @description Epoch millis
             */
            createdAt: number;
            /**
             * Format: int64
             * @description Epoch millis
             */
            updatedAt: number;
        };
        DataSourcePage: {
            items: components["schemas"]["DataSourceResponse"][];
            page: number;
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        DataSourceTestRequest: {
            jira: components["schemas"]["JiraConnectionRequest"];
        };
        ConnectionTestRow: {
            /** @description The probe's short identifier (e.g. myself, project_statuses:ENG). */
            name: string;
            /** @description The Jira endpoint path probed. */
            path: string;
            /** @description Whether a real sync depends on this endpoint. */
            required: boolean;
            ok: boolean;
            /** @description The upstream HTTP status, when the probe ran. */
            status?: number | null;
            /** @description A `JiraFetchException` code on failure (e.g. `AUTHENTICATION_FAILED`, `FORBIDDEN_SCOPE`). */
            code?: string | null;
            /** @description The Jira OAuth/API-token scope this endpoint likely needs, for a failed optional/required row. */
            scopeHint?: string | null;
        };
        ConnectionTestResult: {
            rows: components["schemas"]["ConnectionTestRow"][];
            /** @description Resolved once the `tenant_info` probe succeeds. */
            cloudId?: string | null;
        };
        /** @enum {string} */
        SyncJobKind: "SYNC" | "RECONCILE" | "REPROCESS" | "PURGE";
        /** @enum {string} */
        SyncJobStatus: "PENDING" | "RUNNING" | "SUCCEEDED" | "FAILED" | "CANCELLED";
        SyncJobRequest: {
            /** @description `PURGE` is internal-only and rejected here with `400`. */
            kind: components["schemas"]["SyncJobKind"];
        };
        SyncJobResponse: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            connectionId: number;
            kind: components["schemas"]["SyncJobKind"];
            status: components["schemas"]["SyncJobStatus"];
            /** @description 0 manual, 10 scheduler-enqueued. */
            priority: number;
            /**
             * Format: int32
             * @description Null for scheduler-enqueued jobs.
             */
            requestedByUserId?: number | null;
            /** Format: int64 */
            configRevision: number;
            /**
             * Format: int64
             * @description Epoch millis
             */
            requestedAt: number;
            /**
             * Format: int64
             * @description Epoch millis
             */
            startedAt?: number | null;
            /**
             * Format: int64
             * @description Epoch millis
             */
            finishedAt?: number | null;
            attempt: number;
            maxAttempts: number;
            /**
             * Format: int64
             * @description Epoch millis
             */
            leaseUntil?: number | null;
            /**
             * Format: int64
             * @description Epoch millis
             */
            heartbeatAt?: number | null;
            /**
             * Format: int64
             * @description Epoch millis
             */
            cancelRequestedAt?: number | null;
            currentStream?: string | null;
            progress?: {
                [key: string]: unknown;
            } | null;
            errorCode?: string | null;
            errorDetail?: string | null;
        };
        SyncJobPage: {
            items: components["schemas"]["SyncJobResponse"][];
            page: number;
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        SyncJobActionResult: {
            job: components["schemas"]["SyncJobResponse"];
            /** @description True when an already-open job for the same (connection, kind) was returned instead of a new one. */
            coalesced: boolean;
        };
        /** @description RFC 7807 problem detail. Served as `application/problem+json`; instance is the request path without query parameters. */
        ProblemDetail: {
            /**
             * @description A URI reference identifying the problem type.
             * @default about:blank
             */
            type: string;
            /** @description Short, human-readable summary of the problem type. */
            title: string;
            /** @description HTTP status code. */
            status: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail: string;
            /** @description URI reference of the specific occurrence (the request path). */
            instance: string;
        };
    };
    responses: {
        /** @description Request body must use application/json. A missing body or Content-Type remains a 400. */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Malformed request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Missing or invalid token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Caller is not permitted to perform this action */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Conflict with an existing resource */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Throttled — either the per-IP rate-limit bucket is exhausted (generic detail) or, on /login, the per-account lockout is active (account-specific detail). Both carry a ProblemDetail body. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Request body exceeds the global 10 MiB ceiling — a memory-DoS backstop shared by every endpoint (declared here on the largest-bodied operation; field-level maxLength rules reject oversized values far earlier on ordinary payloads). */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Unexpected server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
    };
    parameters: {
        ResourceId: number;
        /** @description 1-based page index. Defaults to 1. */
        Page: number;
        /** @description Rows per page. Defaults to 20, maximum 100. */
        PageSize: number;
        /**
         * @description Sort spec. Format: `field` (ascending) or `-field` (descending). Multiple fields are
         *     comma-separated, leftmost wins: `sort=-updatedAt,name`. The endpoint declares its
         *     sortable-field whitelist; unknown fields are rejected with `400`. `id` ascending is
         *     always appended as a deterministic tiebreaker.
         */
        Sort: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The app and its database answer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
            /** @description The database did not answer within the probe's budget */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Token issued, or (MFA-enabled accounts) a second-factor challenge */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"] | components["schemas"]["MfaChallengeResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            415: components["responses"]["UnsupportedMediaType"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            /** @description MFA is enabled for the account but this deployment cannot send email */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    verifyMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaVerifyRequest"];
            };
        };
        responses: {
            /** @description Token issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            415: components["responses"]["UnsupportedMediaType"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description A fresh token pair */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            415: components["responses"]["UnsupportedMediaType"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Token revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalServerError"];
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Accepted — if the account exists, an email is on its way */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            415: components["responses"]["UnsupportedMediaType"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            /** @description This deployment cannot send email (password reset unavailable) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    listUsers: {
        parameters: {
            query?: {
                /** @description 1-based page index. Defaults to 1. */
                page?: components["parameters"]["Page"];
                /** @description Rows per page. Defaults to 20, maximum 100. */
                pageSize?: components["parameters"]["PageSize"];
                /**
                 * @description Sort spec. Format: `field` (ascending) or `-field` (descending). Multiple fields are
                 *     comma-separated, leftmost wins: `sort=-updatedAt,name`. The endpoint declares its
                 *     sortable-field whitelist; unknown fields are rejected with `400`. `id` ascending is
                 *     always appended as a deterministic tiebreaker.
                 */
                sort?: components["parameters"]["Sort"];
                name?: string;
                email?: string;
                role?: "ADMIN" | "USER";
                /** @description Feature-flag state filter — must be paired with `featureEnabled` (400 otherwise). */
                feature?: components["schemas"]["Feature"];
                /** @description Strict boolean — only users with `feature` enabled (true) or disabled (false). */
                featureEnabled?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description URL of the new user resource */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation error (blank/too-long name or email, password rules) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Caller is not ADMIN, or attempted to delete their own account */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    setUserDisabledFeatures: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserFeaturesUpdateRequest"];
            };
        };
        responses: {
            /** @description Disabled-feature set replaced */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Caller is not ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalServerError"];
        };
    };
    setUserLanguage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLanguageUpdateRequest"];
            };
        };
        responses: {
            /** @description Language set */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Caller is not the target user and not ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalServerError"];
        };
    };
    changeUserPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordUpdateRequest"];
            };
        };
        responses: {
            /** @description Password updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description New password shorter than 10 characters or longer than 71 UTF-8 bytes */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller is not the target user and not ADMIN, or the required current password is missing/incorrect */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listTeams: {
        parameters: {
            query?: {
                /** @description 1-based page index. Defaults to 1. */
                page?: components["parameters"]["Page"];
                /** @description Rows per page. Defaults to 20, maximum 100. */
                pageSize?: components["parameters"]["PageSize"];
                /**
                 * @description Sort spec. Format: `field` (ascending) or `-field` (descending). Multiple fields are
                 *     comma-separated, leftmost wins: `sort=-updatedAt,name`. The endpoint declares its
                 *     sortable-field whitelist; unknown fields are rejected with `400`. `id` ascending is
                 *     always appended as a deterministic tiebreaker.
                 */
                sort?: components["parameters"]["Sort"];
                name?: string;
                memberId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of teams (rosters collapsed to an active-member count) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamCreateRequest"];
            };
        };
        responses: {
            /** @description Created; `Location` points at the new team */
            201: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The team */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    addTeamMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Added */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    removeTeamMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listDataSources: {
        parameters: {
            query?: {
                /** @description 1-based page index. Defaults to 1. */
                page?: components["parameters"]["Page"];
                /** @description Rows per page. Defaults to 20, maximum 100. */
                pageSize?: components["parameters"]["PageSize"];
                /**
                 * @description Sort spec. Format: `field` (ascending) or `-field` (descending). Multiple fields are
                 *     comma-separated, leftmost wins: `sort=-updatedAt,name`. The endpoint declares its
                 *     sortable-field whitelist; unknown fields are rejected with `400`. `id` ascending is
                 *     always appended as a deterministic tiebreaker.
                 */
                sort?: components["parameters"]["Sort"];
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of data sources */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataSourcePage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createDataSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DataSourceRequest"];
            };
        };
        responses: {
            /** @description Created; `Location` points at the new data source */
            201: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataSourceResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalServerError"];
        };
    };
    testDataSourceAdHoc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DataSourceTestRequest"];
            };
        };
        responses: {
            /** @description The probe results (never a failure status — see the row shapes) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionTestResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    testDataSourceStored: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The probe results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionTestResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getDataSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The data source */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataSourceResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateDataSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DataSourceRequest"];
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteDataSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listSyncJobs: {
        parameters: {
            query?: {
                /** @description 1-based page index. Defaults to 1. */
                page?: components["parameters"]["Page"];
                /** @description Rows per page. Defaults to 20, maximum 100. */
                pageSize?: components["parameters"]["PageSize"];
                /**
                 * @description Sort spec. Format: `field` (ascending) or `-field` (descending). Multiple fields are
                 *     comma-separated, leftmost wins: `sort=-updatedAt,name`. The endpoint declares its
                 *     sortable-field whitelist; unknown fields are rejected with `400`. `id` ascending is
                 *     always appended as a deterministic tiebreaker.
                 */
                sort?: components["parameters"]["Sort"];
                kind?: components["schemas"]["SyncJobKind"];
                status?: components["schemas"]["SyncJobStatus"];
            };
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of sync jobs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJobPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    requestSyncJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncJobRequest"];
            };
        };
        responses: {
            /** @description Accepted (queued or coalesced with an already-open job) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJobActionResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getSyncJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
                jobId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The sync job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJobResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    cancelSyncJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
                jobId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation accepted (or already in effect) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJobResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
